#!/bin/bash 
path="/tmp/`md5 -q $0`"; (head -n3 $0; cat $0 | tail -n+4 | sort) > $path; mv $path $0; chmod +x $0; exit

[ ] draw control signals as arrows
[ ] add constant green signal (to measure lane changing model quality)
[ ] implement IDM
[ ] implement rules for turns (right -> right, left -> left)
    [ ] pick lane on the current road to perform turn
    [ ] choose left/forward/right direction and than pick lane
[ ] show statistics (num cars/roads/junctions, average speed/waiting time) etc
    [ ] implement methods to measure
    [ ] text output
    [ ] draw graphs
[ ] scale time
    [ ] metric units
    [ ] implement GUI trackbar
[X] OOP, classes, application
[X] Trajectory class. Contains currentLine and nextLine, allow cars to occupy 2 lanes at once
[X] change lanes in the middle of a road
[X] create cars
[X] create roads
[X] don’t go back on the junction
[X] draw lines
[X] flexible time intervals for the lights
[X] get rid of getters, replace with properties
[X] get rid of tempRoad
[X] highlight junctions
[X] id to objects and fix serialization (avoid references problems)
[X] implement geometry — need Rect (as Polygon), Point, Segment, GridCell
[X] linter
[X] move junctions holding alt
[X] number of lanes should be equal to the intersection length
[X] roads should be connected to their graphical representation, draw cars exactly on the road
[X] save roads to json
[X] scale and scroll map
[X] simulate movement
[X] use storage instead of cookies + serialize/deserialize
